// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package sqlcgen

import (
	"context"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (task_id, user_id, body)
VALUES ($1, $2, $3)
RETURNING id, task_id, user_id, body, created_at, updated_at
`

type CreateCommentParams struct {
	TaskID int64
	UserID int64
	Body   string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment, arg.TaskID, arg.UserID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :execrows
DELETE FROM comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteComment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getComment = `-- name: GetComment :one
SELECT id, task_id, user_id, body, created_at, updated_at
FROM comments
WHERE id = $1
`

func (q *Queries) GetComment(ctx context.Context, id int64) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCommentsByTask = `-- name: ListCommentsByTask :many
SELECT id, task_id, user_id, body, created_at, updated_at
FROM comments
WHERE task_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListCommentsByTask(ctx context.Context, taskID int64) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommentBody = `-- name: UpdateCommentBody :one
UPDATE comments
SET body = $2, updated_at = now()
WHERE id = $1
RETURNING id, task_id, user_id, body, created_at, updated_at
`

type UpdateCommentBodyParams struct {
	ID   int64
	Body string
}

func (q *Queries) UpdateCommentBody(ctx context.Context, arg UpdateCommentBodyParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, updateCommentBody, arg.ID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
