// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID        int64
	TaskID    int64
	UserID    int64
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Project struct {
	ID          int64
	Name        string
	Description string
	CreatedAt   time.Time
}

type ProjectMember struct {
	ProjectID int64
	UserID    int64
	Role      string
}

type Task struct {
	ID          int64
	ProjectID   int64
	Title       string
	Description string
	Status      string
	AssigneeID  sql.NullInt64
	CreatedBy   int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID           int64
	Email        string
	Name         string
	PasswordHash string
	CreatedAt    time.Time
}
