// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const addProjectMember = `-- name: AddProjectMember :exec
INSERT INTO project_members (project_id, user_id, role)
VALUES ($1, $2, $3)
`

type AddProjectMemberParams struct {
	ProjectID int64
	UserID    int64
	Role      string
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.ExecContext(ctx, addProjectMember, arg.ProjectID, arg.UserID, arg.Role)
	return err
}

const countProjectOwners = `-- name: CountProjectOwners :one
SELECT count(*)
FROM project_members
WHERE project_id = $1 AND role = 'owner'
`

func (q *Queries) CountProjectOwners(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectOwners, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, description)
VALUES ($1, $2)
RETURNING id, name, description, created_at
`

type CreateProjectParams struct {
	Name        string
	Description string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProject = `-- name: GetProject :one
SELECT id, name, description, created_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT pm.user_id, u.email, u.name, pm.role
FROM project_members pm
JOIN users u ON u.id = pm.user_id
WHERE pm.project_id = $1 AND pm.user_id = $2
`

type GetProjectMemberParams struct {
	ProjectID int64
	UserID    int64
}

type GetProjectMemberRow struct {
	UserID int64
	Email  string
	Name   string
	Role   string
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (GetProjectMemberRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectMember, arg.ProjectID, arg.UserID)
	var i GetProjectMemberRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Name,
		&i.Role,
	)
	return i, err
}

const getProjectMemberRole = `-- name: GetProjectMemberRole :one
SELECT role
FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type GetProjectMemberRoleParams struct {
	ProjectID int64
	UserID    int64
}

func (q *Queries) GetProjectMemberRole(ctx context.Context, arg GetProjectMemberRoleParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getProjectMemberRole, arg.ProjectID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT pm.user_id, u.email, u.name, pm.role
FROM project_members pm
JOIN users u ON u.id = pm.user_id
WHERE pm.project_id = $1
ORDER BY pm.user_id
`

type ListProjectMembersRow struct {
	UserID int64
	Email  string
	Name   string
	Role   string
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID int64) ([]ListProjectMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectMembersRow
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Name,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByUser = `-- name: ListProjectsByUser :many
SELECT p.id, p.name, p.description, p.created_at, pm.role
FROM projects p
JOIN project_members pm ON pm.project_id = p.id
WHERE pm.user_id = $1
ORDER BY p.created_at DESC, p.id DESC
`

type ListProjectsByUserRow struct {
	ID          int64
	Name        string
	Description string
	CreatedAt   time.Time
	Role        string
}

func (q *Queries) ListProjectsByUser(ctx context.Context, userID int64) ([]ListProjectsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsByUserRow
	for rows.Next() {
		var i ListProjectsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProjectMember = `-- name: LockProjectMember :one
SELECT user_id
FROM project_members
WHERE project_id = $1 AND user_id = $2
FOR SHARE
`

type LockProjectMemberParams struct {
	ProjectID int64
	UserID    int64
}

// 担当者にする前に、メンバーの行を共有ロックする。並行するメンバー削除は、この確認が終わるまで待つ。
func (q *Queries) LockProjectMember(ctx context.Context, arg LockProjectMemberParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, lockProjectMember, arg.ProjectID, arg.UserID)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const lockProjectOwners = `-- name: LockProjectOwners :many
SELECT user_id
FROM project_members
WHERE project_id = $1 AND role = 'owner'
ORDER BY user_id
FOR UPDATE
`

// owner の降格・削除の判定用。owner の行をロックし、並行する別の降格・削除を待たせる
// (ロック順を user_id 順に固定して、デッドロックを避ける)。
func (q *Queries) LockProjectOwners(ctx context.Context, projectID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, lockProjectOwners, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectMember = `-- name: RemoveProjectMember :execrows
DELETE FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type RemoveProjectMemberParams struct {
	ProjectID int64
	UserID    int64
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeProjectMember, arg.ProjectID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = COALESCE($1::text, name),
    description = COALESCE($2::text, description)
WHERE id = $3
RETURNING id, name, description, created_at
`

type UpdateProjectParams struct {
	Name        sql.NullString
	Description sql.NullString
	ID          int64
}

// 指定された項目(NULL でないもの)だけを更新する。取得→上書きにすると、並行する別項目の更新を消してしまうため。
func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject, arg.Name, arg.Description, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const updateProjectMemberRole = `-- name: UpdateProjectMemberRole :execrows
UPDATE project_members
SET role = $3
WHERE project_id = $1 AND user_id = $2
`

type UpdateProjectMemberRoleParams struct {
	ProjectID int64
	UserID    int64
	Role      string
}

func (q *Queries) UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProjectMemberRole, arg.ProjectID, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
