// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countSearchTasks = `-- name: CountSearchTasks :one
SELECT count(*)
FROM tasks t
JOIN project_members pm ON pm.project_id = t.project_id AND pm.user_id = $1
WHERE ($2::bigint IS NULL OR t.project_id = $2::bigint)
  AND ($3::text IS NULL OR t.status = $3::text)
  AND ($4::bigint IS NULL OR t.assignee_id = $4::bigint)
  AND (
    $5::text IS NULL
    OR t.title ILIKE '%' || $5::text || '%' ESCAPE '\'
    OR t.description ILIKE '%' || $5::text || '%' ESCAPE '\'
  )
`

type CountSearchTasksParams struct {
	UserID     int64
	ProjectID  sql.NullInt64
	Status     sql.NullString
	AssigneeID sql.NullInt64
	Q          sql.NullString
}

func (q *Queries) CountSearchTasks(ctx context.Context, arg CountSearchTasksParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchTasks,
		arg.UserID,
		arg.ProjectID,
		arg.Status,
		arg.AssigneeID,
		arg.Q,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, title, description, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, title, description, status, assignee_id, created_by, created_at, updated_at
`

type CreateTaskParams struct {
	ProjectID   int64
	Title       string
	Description string
	CreatedBy   int64
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.CreatedBy,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :execrows
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTask = `-- name: GetTask :one
SELECT id, project_id, title, description, status, assignee_id, created_by, created_at, updated_at
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchTasks = `-- name: SearchTasks :many
SELECT t.id, t.project_id, t.title, t.description, t.status, t.assignee_id, t.created_by, t.created_at, t.updated_at
FROM tasks t
JOIN project_members pm ON pm.project_id = t.project_id AND pm.user_id = $1
WHERE ($2::bigint IS NULL OR t.project_id = $2::bigint)
  AND ($3::text IS NULL OR t.status = $3::text)
  AND ($4::bigint IS NULL OR t.assignee_id = $4::bigint)
  AND (
    $5::text IS NULL
    OR t.title ILIKE '%' || $5::text || '%' ESCAPE '\'
    OR t.description ILIKE '%' || $5::text || '%' ESCAPE '\'
  )
ORDER BY t.updated_at DESC, t.id DESC
LIMIT $7 OFFSET $6
`

type SearchTasksParams struct {
	UserID     int64
	ProjectID  sql.NullInt64
	Status     sql.NullString
	AssigneeID sql.NullInt64
	Q          sql.NullString
	PageOffset int32
	PageLimit  int32
}

// 検索は「呼び出しユーザーが所属するプロジェクト」に JOIN で必ず絞る(権限の漏れを SQL 側でも防ぐ)。
// q は呼び出し側で LIKE のメタ文字(\ % _)をエスケープして渡す。
func (q *Queries) SearchTasks(ctx context.Context, arg SearchTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, searchTasks,
		arg.UserID,
		arg.ProjectID,
		arg.Status,
		arg.AssigneeID,
		arg.Q,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.AssigneeID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unassignTasksInProject = `-- name: UnassignTasksInProject :exec
UPDATE tasks
SET assignee_id = NULL, updated_at = now()
WHERE project_id = $1 AND assignee_id = $2
`

type UnassignTasksInProjectParams struct {
	ProjectID  int64
	AssigneeID sql.NullInt64
}

// メンバーをプロジェクトから外すとき、そのプロジェクトで担当していた Task の担当者を解除する。
func (q *Queries) UnassignTasksInProject(ctx context.Context, arg UnassignTasksInProjectParams) error {
	_, err := q.db.ExecContext(ctx, unassignTasksInProject, arg.ProjectID, arg.AssigneeID)
	return err
}

const updateTaskAssignee = `-- name: UpdateTaskAssignee :one
UPDATE tasks
SET assignee_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, project_id, title, description, status, assignee_id, created_by, created_at, updated_at
`

type UpdateTaskAssigneeParams struct {
	ID         int64
	AssigneeID sql.NullInt64
}

func (q *Queries) UpdateTaskAssignee(ctx context.Context, arg UpdateTaskAssigneeParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskAssignee, arg.ID, arg.AssigneeID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskContent = `-- name: UpdateTaskContent :one
UPDATE tasks
SET title = $2, description = $3, updated_at = now()
WHERE id = $1
RETURNING id, project_id, title, description, status, assignee_id, created_by, created_at, updated_at
`

type UpdateTaskContentParams struct {
	ID          int64
	Title       string
	Description string
}

func (q *Queries) UpdateTaskContent(ctx context.Context, arg UpdateTaskContentParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskContent, arg.ID, arg.Title, arg.Description)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, project_id, title, description, status, assignee_id, created_by, created_at, updated_at
`

type UpdateTaskStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskStatus, arg.ID, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
